Add style-guide.md with clear formatting and styling rules
kadenzipfel/smart-contract-vulnerabilities pull request #47
Opened 2024-05-22 15:54 UTC by mawutory

This style guide was generated based on the style and formatting used in pre-existing texts. It is suitable to serve as the base guide while flexible enough to be fine-tuned over time. Fixes #38

2024-05-22 16:50 UTC, kadenzipfel requested changes
This is looking really good so far! I would also indicate that when you add a new vulnerability you also need to add a link to it in the README

2024-05-22 16:50 UTC, kadenzipfel commented on style-guide.md
> +- *Affected Chains:* Specify which EVM-compatible chains are susceptible to the vulnerability. Highlight any chain-specific considerations.
I would mark this as optional since it's only necessary if it doesn't affect all EVM chains (which most probably do)

2024-05-22 16:50 UTC, kadenzipfel commented on style-guide.md
> +- *Detection and Mitigation:* Outline recommended methods for detecting the vulnerability during smart contract audits and suggest mitigation strategies for developers. Tools and best practices can b
I would also mark this as optional

2024-05-23 07:34 UTC, mawutory commented on style-guide.md
> +- *Affected Chains:* Specify which EVM-compatible chains are susceptible to the vulnerability. Highlight any chain-specific considerations.
yes

2024-05-23 07:41 UTC, mawutory commented on style-guide.md
> +- *Detection and Mitigation:* Outline recommended methods for detecting the vulnerability during smart contract audits and suggest mitigation strategies for developers. Tools and best practices can b
roger that

2024-05-23 08:13 UTC, mawutory commented
Okay, thanks for the feedback. I added a line on updating the README, under Content Guidelines like this:

"When you add a new vulnerability and its corresponding markdown file, remember to update `README.md` with the new entry. "

I will be updating the PR with the changes.

2024-05-23 16:15 UTC, rakesh0x7 reviewed
@mawutory Thank you for creating the style guide. It looks great and will be very helpful for our contributors.

@kadenzipfel, I was wondering where we should reference this style guide so that contributors can easily access it. Should we add a link to it in the README or place it somewhere else?

2024-05-24 00:15 UTC, kadenzipfel commented
> @kadenzipfel, I was wondering where we should reference this style guide so that contributors can easily access it. Should we add a link to it in the README or place it somewhere else?

I think for now it's ok to just have it in the PR template, but open to other opinions

2024-05-24 00:16 UTC, kadenzipfel approved these changes

2024-05-24 00:17 UTC, merged