Update Delegatecall to Untrusted Callee
kadenzipfel/smart-contract-vulnerabilities pull request #92
Opened 2024-06-14 11:51 UTC by rakesh0x7

## Related Issue

- Closes: (Link the issue this pull request addresses)  

## Checklist

- [X] I have read and followed the [style guide](https://github.com/kadenzipfel/smart-contract-vulnerabilities/blob/master/style-guide.md)

### Describe the changes you've made:

Updated the "Delegatecall to Untrusted Callee" issue to example, mitigation.

2024-06-18 23:56 UTC, kadenzipfel requested changes

2024-06-18 23:56 UTC, kadenzipfel commented on vulnerabilities/delegatecall-untrusted-callee.md
> +}
This isn't really realistic because it's actually delegatecalling to an intended callee that allows for exploit. It would be more realistic if anyone could provide an address to delegatecall to and that was how it could be exploited

2024-06-19 09:50 UTC, rakesh0x7 commented on vulnerabilities/delegatecall-untrusted-callee.md
> +}
I took a new proxy example from SWC [Registry](https://swcregistry.io/docs/SWC-112/#references) and I made some modifications, please review it :D

2024-07-28 20:36 UTC, kadenzipfel approved these changes

2024-07-28 20:36 UTC, merged